CREATE TABLE lessons (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  video_link TEXT,
  position INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  update_at TIMESTAMP NOT NULL,
  course_link TEXT NOT NULL
);

CREATE TABLE courses (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  update_at TIMESTAMP NOT NULL
);

CREATE TABLE modules (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  update_at TIMESTAMP NOT NULL
);

CREATE TABLE programs (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  price INT NOT NULL,
  program_type VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  update_at TIMESTAMP NOT NULL
);